# -*- coding: utf-8 -*-
"""Quest 0:Prueba diagnóstic-Julián Botello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUhrRfeBQ4PIF8tWS0mDgFHE8ZYegfn-

1. Programa que les pida el nombre
"""

Nombre=input("Escriba su nombre")
print(Nombre)

"""2. Programa que determina si un numero es positivo o negativo"""

A=int(input("Escriba un número"))
if A<0:
 print("El número es Negativo")
else:
 print("El número es Positivo")

"""3. Programa que detemina la edad de una persona"""

Edad=int(input("Ingrese su edad: "))
if Edad<1:
  print("edad no valida")
else:
 if Edad<18:
   print("Usted es menor de edad")
 else:
   print("Usted es mayor de edad")

"""4.Programa que imprime el número mayor"""

A=float(input("Ingrese el primer número: "))
B=float(input("Ingrese el segundo número: "))
if A>B:
  print(A)
else:
  print(B)

"""5.Programa para calificar"""

Calificasion=int(input("Ingrse la calificasion del estudiante (recuerde que debe de ser de 0 a 100): "))
while Calificasion<0 or Calificasion>100:
  print("el valor no es valido, porfavor vuelva a ingresar la nota")
  Calificasion=int(input("Ingrse la calificasion del estudiante (recuerde que debe de ser de 0 a 100): "))
if Calificasion>=60:
  print("El estudiante aprobo el curso")
else:
  print("Es estudiante reprobo el curso")

"""6.Programa pra comparar tres numeros"""

A=float(input("Ingrese el primer número: "))
B=float(input("Ingrese el segundo número: "))
C=float(input("Ingrese el tercer número: "))
if A>B and A>C:
  print("El número mayor es: ",A)
elif B>A and B>C:
  print("El número mayor es: ",B)
else:
  print("El número mayor es: ",C)

"""7.Indicador de año biciesto"""

from ast import mod
Año=int(input("Ingrese el año en el que se encuentra: "))
while Año<0:
  print("El año ingresado no es valido, porfavor vuelva a ingresar la fecha")
  Año=int(input("Ingrese el año en el que se encuentra: "))
if Año mod 4 = 0:
  print("El año es biciesto")
else:
  print("El año no es biciesto")